# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e42fe96fb7f6b5e8bcdab8896e3addc0e25b67aaebe7b233967a2e8fb1f89f4121ab851969770cda698878539d66ee57b96e09d9830dc45338c7ff5efb2d265

test:
  secret_key_base: e9f093d424373447d5592c368a544cba35c15bc81a8f35980ff4080b0455a44a56a645adf2819082c0f362f97072d91d329850c08c16702b93d89df5176e812e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
